# Generated by Django 4.0.6 on 2022-07-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0002_cargo_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='oficina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestor.oficina'),
            preserve_default=False,
        ),
    ]
