# Generated by Django 4.0.6 on 2022-07-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0003_cargo_oficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
    ]
