# Generated by Django 4.0.6 on 2022-07-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0004_remove_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestor.cargo'),
            preserve_default=False,
        ),
    ]
