# Generated by Django 4.0.6 on 2022-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0005_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nac',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('O', 'OTROS')], default='v', max_length=1, verbose_name='Nacionalidad'),
        ),
    ]
