# Generated by Django 4.0.6 on 2022-07-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0006_empleado_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nac',
            field=models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO')], default='v', max_length=1, verbose_name='Nacionalidad'),
        ),
    ]
