# Generated by Django 4.0.6 on 2022-09-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor', '0008_alter_empleado_fecha_egreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codpatria',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='Codigo Patria'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='serialpatria',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='Serial Patria'),
        ),
    ]
